import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Carousel from "@/components/Carousel";
import TestimonialCarousel from "@/components/TestimonialCarousel";
import PortfolioCarousel from "@/components/PortfolioCarousel";
import Categories from "@/components/Categories";
import ImgCarouselContent from "@/components/ImgCarouselContent";
import HomeOwlSlider from "@/components/HomeOwlSlider";

const inter = Inter({ subsets: ["latin"] });

const pic4 = "/assets/images/main/img.jpg";
const pic5 = "/assets/images/main/time.jpg";
const pic6 = "/assets/images/main/venue.jpg";
const bgimg2 = "/assets/images/background/bg-map.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          AISEEF - ASEAN INNOVATIVE SCIENCE ENVIRONMENTAL AND ENTREPRENEUR FAIR
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section>
        <div className="page-content bg-white">
          {/*  Slider Banner */}
          <div className="owl-slider-banner main-slider">
            <HomeOwlSlider />
          </div>
          {/*  Slider Banner */}
          <div className="content-block">
            {/* <!-- About Us --> */}
            <div className="section-full bg-white content-inner-1 about-us">
              <div className="container">
                <div className="row">
                  <div className="col-lg-7 col-md-8">
                    <div className="about-box row">
                      <div className="col-lg-4">
                        <h2 className="box-title m-tb0">
                          About Us
                          <span className="bg-primary"></span>
                        </h2>
                        <h4 className="text-gray-dark">
                          Share your experiences to us
                        </h4>
                      </div>
                      <div className="col-lg-8">
                        <p>
                          &quot;Innovation&quot; is a must in today&apos;s
                          modern era. This simple word demands a huge result
                          within creating a new work which is called
                          &quot;Invention&quot;.
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-5 col-md-4 about-img">
                    <Image
                      src={pic4}
                      alt="About Us"
                      layout="responsive"
                      width={500}
                      height={300}
                    />
                  </div>
                </div>
              </div>
            </div>
            {/* <!-- About Us End --> */}
            
            {/* <!-- Our Services --> */}
            <div className="section-full content-inner-2" id="Categories">
              <div className="container">
                <div className="section-head text-black text-center">
                  <h2 className="box-title m-tb0">
                    Categories <span className="bg-primary"></span>
                  </h2>
                  <p>Which categories for joining with us?</p>
                </div>
              </div>
              <div className="development-box">
                <div className="container">
                  <Categories />
                </div>
              </div>
            </div>
            <div className="section-full content-inner-1 mfp-gallery">
              <div className="container-fluid">
                <div className="section-head text-center">
                  <h4 className="text-gray-dark m-b10">Event Story</h4>
                  <h2 className="box-title m-tb0">
                    Our Success Event
                    <br /> 2020 - 2024
                    <span className="bg-primary"></span>
                  </h2>
                </div>
                <PortfolioCarousel />
              </div>
            </div>
            <div className="section-full bg-white content-inner-1 about-us">
              <div className="container">
                <div className="row">
                  <div className="col-lg-7 col-md-8">
                    <div className="about-box row">
                      <div className="col-lg-4">
                        <h2 className="box-title m-tb0">
                          Time & Venue
                          <span className="bg-primary"></span>
                        </h2>
                      </div>
                      <div className="col-lg-5 col-md-4 about-img">
                    <Image
                      src={pic5}
                      alt="About Us"
                      layout="responsive"
                      width={500}
                      height={300}
                    />
                  </div>
                    </div>
                  </div>
                  <div className="col-lg-5 col-md-4 about-img">
                    <Image
                      src={pic6}
                      alt="About Us"
                      layout="responsive"
                      width={500}
                      height={300}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div
              className="section-full content-inner"
              style={{
                backgroundImage: `url(${bgimg2})`,
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
              }}
              id="Testimonial"
            >
              <div className="container">
                <div className="section-head text-center">
                  <h2 className="box-title m-tb0">
                    Our Testimonials
                    <span className="bg-primary"></span>
                  </h2>
                  <p>Success stories from participants who joined our event</p>
                </div>
                <div className="section-content m-b30">
                  <TestimonialCarousel />
                </div>
              </div>
            </div>
            {/* <!-- Testimonials END --> */}
          </div>
        </div>
      </section>
      <div className="section-full bg-primary-dark p-tb15">
        <div className="container">
          <Carousel />
        </div>
      </div>
      <Footer />
    </>
  );
}
